sudo: false
language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
cache: npm
notifications:
  email: false
branches:
  only:
    - master
install: npm install
script: npm run test:coverage
jobs:
  include:
    - stage: release
      node_js: '10'
      script: npm run semantic-release
